#!/usr/bin/env python3
"""Merge the extracted KiCad menu tree with the curated headless bindings.

Inputs
    src/kicad_mcp/menus/menu_catalog.json      (generated by extract_kicad_menus.py)
    docs/compatibility/kicad-menu-bindings.yaml (curated source of truth)

Output
    src/kicad_mcp/menus/menu_index.json        (generated; shipped in the wheel)

The runtime reads only the generated JSON, so the server needs no YAML dependency —
the same split the capability-parity matrix uses.

Regenerate with:
    uv run python scripts/build_menu_index.py
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import yaml

CHANNELS = ("mcp", "cli", "file", "ipc", "gui-only")
STATUSES = ("covered", "partial", "gap", "gui-only")


def _walk(items: list[dict[str, Any]]) -> Iterator[dict[str, Any]]:
    for item in items:
        if item["kind"] == "action":
            yield item
        elif item["kind"] == "submenu":
            yield from _walk(item["items"])


def _resolve_binding(action_name: str, bindings: dict[str, Any]) -> dict[str, Any]:
    """Resolve one action to its binding: override, then namespace rule, then default."""
    override = bindings["overrides"].get(action_name)
    if override is not None:
        return {"source": "override", **override}
    for rule in bindings["namespace_rules"]:
        if action_name.startswith(rule["prefix"]):
            resolved = {key: value for key, value in rule.items() if key != "prefix"}
            return {"source": f"rule:{rule['prefix']}", **resolved}
    return {"source": "default", **bindings["default_binding"]}


def build_index(catalog: dict[str, Any], bindings: dict[str, Any]) -> dict[str, Any]:
    """Join the menu catalog with bindings and compute coverage statistics."""
    if catalog["kicad_version"] != bindings["kicad_version"]:
        print(
            f"! version mismatch: catalog {catalog['kicad_version']} "
            f"vs bindings {bindings['kicad_version']}",
            file=sys.stderr,
        )

    resolved: dict[str, dict[str, Any]] = {}
    placements: dict[str, list[dict[str, Any]]] = {}

    for frame in catalog["frames"]:
        for menu in frame["menus"]:
            for item in _walk(menu["items"]):
                name = item["action_name"]
                if name not in resolved:
                    binding = _resolve_binding(name, bindings)
                    channel = binding.get("channel", "gui-only")
                    status = binding.get("status", "gui-only")
                    if channel not in CHANNELS:
                        raise ValueError(f"{name}: unknown channel {channel!r}")
                    if status not in STATUSES:
                        raise ValueError(f"{name}: unknown status {status!r}")
                    resolved[name] = {
                        "action_name": name,
                        "action_ref": item["action_ref"],
                        "label": item["label"],
                        "friendly_name": item.get("friendly_name", ""),
                        "tooltip": item.get("tooltip", ""),
                        "default_hotkey": item.get("default_hotkey", ""),
                        "channel": channel,
                        "status": status,
                        "mcp_tool": binding.get("mcp_tool", ""),
                        "cli_command": binding.get("cli_command", []),
                        "notes": (binding.get("notes") or "").strip(),
                        "binding_source": binding["source"],
                    }
                placements.setdefault(name, []).append({"frame": frame["id"], "path": item["path"]})

    for name, entry in resolved.items():
        entry["placements"] = placements[name]

    # Coverage: gui-only rows are a KiCad limit, not a gap here, so they leave the
    # denominator — the same convention the capability-parity matrix uses.
    def _stats(names: list[str]) -> dict[str, Any]:
        counts = dict.fromkeys(STATUSES, 0)
        for name in names:
            counts[resolved[name]["status"]] += 1
        total = len(names)
        denominator = total - counts["gui-only"]
        driven = counts["covered"] + counts["partial"]
        return {
            "total": total,
            "covered": counts["covered"],
            "partial": counts["partial"],
            "gap": counts["gap"],
            "gui_only": counts["gui-only"],
            "denominator": denominator,
            "coverage_pct": round(100.0 * counts["covered"] / denominator, 1)
            if denominator
            else 0.0,
            "driven_pct": round(100.0 * driven / denominator, 1) if denominator else 0.0,
        }

    per_frame: dict[str, Any] = {}
    for frame in catalog["frames"]:
        names: list[str] = []
        for menu in frame["menus"]:
            names.extend(item["action_name"] for item in _walk(menu["items"]))
        per_frame[frame["id"]] = {
            "title": frame["title"],
            "menu_items": len(names),
            **_stats(sorted(set(names))),
        }

    return {
        "schema_version": 1,
        "kicad_version": catalog["kicad_version"],
        "generator": "scripts/build_menu_index.py",
        "channels": bindings["channels"],
        "statuses": bindings["statuses"],
        "frames": [
            {
                "id": frame["id"],
                "title": frame["title"],
                "menus": frame["menus"],
            }
            for frame in catalog["frames"]
        ],
        "actions": dict(sorted(resolved.items())),
        "coverage": {
            "overall": _stats(sorted(resolved)),
            "frames": per_frame,
        },
    }



def render_markdown(index: dict[str, Any]) -> str:
    """Render the human-readable coverage report shipped in docs/compatibility."""
    overall = index["coverage"]["overall"]
    lines = [
        "# KiCad Menu Coverage (generated)",
        "",
        "Machine-generated from KiCad's own C++ menu sources plus "
        "`docs/compatibility/kicad-menu-bindings.yaml`. Refresh with "
        "`uv run python scripts/extract_kicad_menus.py` then "
        "`uv run python scripts/build_menu_index.py`.",
        "",
        f"KiCad baseline: `{index['kicad_version']}`",
        "",
        (
            f"**Overall: {overall['covered']} / {overall['denominator']} "
            f"headlessly-reachable menu commands driven = "
            f"{overall['coverage_pct']}%** "
            f"({overall['partial']} partial, {overall['gap']} gap; "
            f"{overall['gui_only']} GUI-only with no KiCad API, excluded from the "
            "denominator)."
        ),
        "",
        "A command is `gui-only` when KiCad itself offers no cli, ipc or file path for "
        "it. Those are KiCad limits, not gaps in this server, so they leave the "
        "denominator — the same convention the capability-parity matrix uses.",
        "",
        "## Coverage by application frame",
        "",
        "| Frame | Commands | Coverage | Covered | Partial | Gap | GUI-only |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for frame_id, stats in index["coverage"]["frames"].items():
        lines.append(
            f"| `{frame_id}` | {stats['total']} | {stats['coverage_pct']}% | "
            f"{stats['covered']} | {stats['partial']} | {stats['gap']} | "
            f"{stats['gui_only']} |"
        )
    lines.append(
        f"| **Overall (distinct)** | {overall['total']} | **{overall['coverage_pct']}%** | "
        f"{overall['covered']} | {overall['partial']} | {overall['gap']} | "
        f"{overall['gui_only']} |"
    )

    gaps = sorted(
        (entry for entry in index["actions"].values() if entry["status"] == "gap"),
        key=lambda entry: entry["label"].casefold(),
    )
    lines.extend(
        [
            "",
            "## Closeable surface",
            "",
            "Menu commands KiCad exposes outside the GUI that no MCP tool drives yet.",
            "",
            "| Command | Channel | Menu location | Notes |",
            "|---|---|---|---|",
        ]
    )
    for entry in gaps:
        placement = entry["placements"][0]
        location = f"{placement['frame']}: {' > '.join(placement['path'])}"
        notes = entry["notes"].replace("\n", " ").replace("|", "\\|")
        lines.append(
            f"| {entry['label']} | `{entry['channel']}` | {location} | {notes} |"
        )

    partials = sorted(
        (entry for entry in index["actions"].values() if entry["status"] == "partial"),
        key=lambda entry: entry["label"].casefold(),
    )
    lines.extend(
        [
            "",
            "## Partial coverage",
            "",
            "| Command | MCP tool | Notes |",
            "|---|---|---|",
        ]
    )
    for entry in partials:
        notes = entry["notes"].replace("\n", " ").replace("|", "\\|")
        tool = f"`{entry['mcp_tool']}`" if entry["mcp_tool"] else "—"
        lines.append(f"| {entry['label']} | {tool} | {notes} |")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parent.parent
    parser.add_argument(
        "--catalog", type=Path, default=root / "src/kicad_mcp/menus/menu_catalog.json"
    )
    parser.add_argument(
        "--bindings", type=Path, default=root / "docs/compatibility/kicad-menu-bindings.yaml"
    )
    parser.add_argument("--out", type=Path, default=root / "src/kicad_mcp/menus/menu_index.json")
    parser.add_argument(
        "--markdown",
        type=Path,
        default=root / "docs/compatibility/kicad-menu-coverage.generated.md",
    )
    args = parser.parse_args()

    catalog = json.loads(args.catalog.read_text(encoding="utf-8"))
    bindings = yaml.safe_load(args.bindings.read_text(encoding="utf-8"))

    index = build_index(catalog, bindings)
    args.out.write_text(json.dumps(index, indent=1, sort_keys=False) + "\n", encoding="utf-8")
    args.markdown.write_text(render_markdown(index), encoding="utf-8")

    overall = index["coverage"]["overall"]
    print(f"Wrote {args.out} ({args.out.stat().st_size / 1024:.0f} KiB)")
    print(f"Wrote {args.markdown}")
    print(
        f"  {overall['total']} distinct menu commands: "
        f"{overall['covered']} covered, {overall['partial']} partial, "
        f"{overall['gap']} gap, {overall['gui_only']} GUI-only"
    )
    print(
        f"  headless coverage {overall['coverage_pct']}% "
        f"({overall['driven_pct']}% at least partially driven) "
        f"of {overall['denominator']} reachable commands"
    )
    unresolved = [
        name for name, entry in index["actions"].items() if entry["binding_source"] == "default"
    ]
    if unresolved:
        print(f"  ! {len(unresolved)} commands fell through to the default binding:")
        for name in unresolved[:20]:
            print(f"      {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
